### ISSUE TITLE
xfce-theme-greenbird source not point to github

### ISSUE THREAD

**Issue by jristz** [manjaro/packages-extra#1]
actually the package xfce-theme-greenbird in packages-extra have they url and source point to manjaro.org but you already migrated to github.
some users could try to build it from the PKGBUILD and will have problems.

you can update the source of those themes that now are hosted here in github, so users could build trhow your upstream PKGBUILD without problems

**Comment by philmmanjaro** [comment]
If still some PKGBUILDs miss some sources, tell us.
