### ISSUE TITLE
Can't makepkg linux40-broadcom-wl (missing linux-40.patch)

### ISSUE THREAD

**Issue by jtojnar** [manjaro/packages-extra#10]
==> Making package: linux40-broadcom-wl 6.30.223.141-1 (Thu 23 Apr 14:27:24 CEST 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found broadcom-wl-dkms.conf
==> ERROR: linux-40.patch was not found in the build directory and is not a URL.

**Comment by philmmanjaro** [comment]
fixed with f90e63bf7a7ae3816a19b7bff76a7ee62513bd66
