### ISSUE TITLE
[manjaro-hello] Replace definitely manjaro-welcome

### ISSUE THREAD

**Issue by Huluti** [manjaro/packages-extra#103]
Could we update both PKGBUILD to automatically install **manjaro-hello** instead of **manjaro-welcome**? **manjaro-welcome** is one the latest soft that requires webkitgtk2. We should consider to drop manjaro-welcome from our repos.
What do you think?

**Comment by udeved** [comment]
Sure, we can make manjaro-hello replace manjaro-welcome package, if it is installed.

**Comment by philmmanjaro** [comment]
We have to update the **release announcement** anyway. So yes, we can drop **manjaro-welcome** then ...

**Comment by philmmanjaro** [comment]
https://github.com/manjaro/packages-extra/commit/f1d4d74e8654b5e93b546411652d94c1f68555fb

**Comment by Huluti** [comment]
We don't need **manjaro-features**, **manjaro-features-pre** and **manjaro-features-dev** anymore also.

**Comment by Huluti** [comment]
@udeved could you take a look [about that](https://github.com/manjaro/packages-extra/issues/103#issuecomment-280916735)?

**Comment by Ste74** [comment]
What you mean ?

**Comment by Huluti** [comment]
We still have manjaro-features, manjaro-features-pre and manjaro-features-dev in ours repos but it was only used by manjaro-welcome. PKGBUILD was removed by philm in f1d4d74.

**Comment by oberon2007** [comment]
They are no longer. I just killed them, including manjaro-welcome :gun:
