### ISSUE TITLE
[manjaro-faces] Still used?

### ISSUE THREAD

**Issue by Huluti** [manjaro/packages-extra#104]
The **manjaro-faces** package in our repos has this old url: https://git.manjaro.org/core/live-installer. It seems to be very old (0.8.8rc1-1).
Do we still need this package?

**Comment by Ste74** [comment]
Ah ah .. no this is an old pkgs for old installer .. i think can be removed from our binary repo ..

**Comment by Huluti** [comment]
I don't find any PKGBUILD in our GitHub repos anymore, but **manjaro-faces** it still in Manjaro's repos despite of https://github.com/manjaro/packages-extra/pull/105. Do we need to do something?

**Comment by udeved** [comment]
No idea, but I think the package with had the manjaro-faces depend is gone for some time now.
Iirc, it was old cli installer or something like that.

**Comment by Huluti** [comment]
Yes, but we have remove all PKGBUILD that refers to it. Just wondering why it's still in the repos. Who can remove it?

**Comment by udeved** [comment]
I can remove it.
Need to move some pkgs anyway. ;)

**Comment by Huluti** [comment]
Great! So, I close the issue. Thank's!
