### ISSUE TITLE
xfwm4 error with xfconf-gtk3

### ISSUE THREAD

**Issue by ThanosApostolou** [manjaro/packages-extra#111]
I see this error:
```
[thanos@thanos-pc ~]$ xfwm4
xfwm4: error while loading shared libraries: libxfconf-0.so.2: cannot open shared object file: No such file or directory
```

I see that the package **xfconf-gtk3** owns the file **libxfconf-0.so.3**. I tried to build **xfwm4-git** from AUR, after I installed **xfconf-gtk3**, but I get the same error. Is it possible to build also **xfwm4** against the new library and include it to xfce4-gtk3 group? Because without it the whole group is not usable...

**Comment by philmmanjaro** [comment]
We have to update this to make it work again. Currently it is broken do the given fact. It is already on our todo list.

**Comment by ThanosApostolou** [comment]
Glad to know :smile: Feel free to close this if want, since it's already on the todo list, or leave it open and close it when it's done.. your choice...

**Comment by ThanosApostolou** [comment]
Same error even with the latest packages. Seems that for some reason it is built against library **libxfconf-0.so.2**.

**Comment by oberon2007** [comment]
@ThanosApostolou can you please try with this one?
```
sudo pacman -U http://www.oberon.at/oberon/xfwm4-gtk3-4.13.0-1.1-x86_64.pkg.tar.xz
```

**Comment by oberon2007** [comment]
No forget it 😉 doesn't work either...

**Comment by oberon2007** [comment]
It might actually be **libxfce4ui-gtk3** that needs a rebuild 😉 I'll try that now.

**Comment by oberon2007** [comment]
**libxfce4ui** fails to build without the latest **libxfce4util**
I'm trying to update the whole bunch now 🤓 will need to add a **libxfce4util-gtk3** for that... 🙄

**Comment by oberon2007** [comment]
now **xfce4-session** is unhappy - wo that one next 😆

**Comment by oberon2007** [comment]
**xfce4-settings**, **xfce4-power-manager** ... it's gettings ridiculous.

**Comment by oberon2007** [comment]
Now **panel**, **thunar**, **xfdesktop** 😁

**Comment by oberon2007** [comment]
64bit pkgs are in unstable, will do 32bit a little later. I still see some less fatal errors in **.xsession-errors** and I have some strange graphics issues going on here - but someone with a clean Xfce install should look a little more into that. @philmmanjaro ?
In any case the session launches successfully again.
I didn't rebuild **garcon** and **exo** since they didn't have any library issues like the other pkgs and their git has no real changes. Doesn't seem to affect the other pkgs as far as I can see.
We'll have to rebuild the whole pile quite soon anyway I guess ... 😜

**Comment by ThanosApostolou** [comment]
Confirming that xfwm4-gtk3 works now! Good job!

**Comment by oberon2007** [comment]
So you don't have panel and dialog parts disappearing when you mouse over them? Apparently an individual problem then ... ... 😜

**Comment by ThanosApostolou** [comment]
Sorry I forgot to say that I use xfwm4 on MATE desktop. I have installed xfce4-gtk3, with which I've noticed some weird stuff, but I logged in with xfce session only for about 10 secs so I didn't really saw what works and what not. But xfwm4 on MATE works perfectly without issues.

**Comment by oberon2007** [comment]
So, in vbox I don't see these issues... Might be it is just something with my dual user setup i3/xfce, or it has to do with my intel-driver...

**Comment by philmmanjaro** [comment]
XFCE build order is documented [here](http://docs.xfce.org/xfce/building).

**Comment by oberon2007** [comment]
so ... I missed out on exo and garcon - do you think we need to build it again with those in line?

**Comment by philmmanjaro** [comment]
It depends. If it works still, it is OK.
