### ISSUE TITLE
linux412-virtualbox currently broken

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-extra#113]
https://github.com/manjaro/packages-core/issues/75
Looks like this should be fixed with **vbox 5.1.23**.

**Comment by philmmanjaro** [comment]
Please try again with current packages in **unstable** branch.

**Comment by philmmanjaro** [comment]
Please test with **v5.1.22-3** in **unstable** branch again.

**Comment by kouros17** [comment]
It's working for me! :+1:
