### ISSUE TITLE
Would you put the PKGBUILD of pamac on AUR?

### ISSUE THREAD

**Issue by JulianLai** [manjaro/packages-extra#115]
It is newer than the one in AUR

**Comment by Ste74** [comment]
Pamac isn't in AUR ? pamac-aur ? You have to ask at maintainer on AUR ;)

**Comment by Huluti** [comment]
pamac is in AUR. This issue can be closed.

**Comment by jonathonf** [comment]
Not sure why the AUR package isn't just called `pamac`... but it is there:

https://aur.archlinux.org/packages/pamac-aur/
