### ISSUE TITLE
xorg-server on github is on 1.17.4 while the binary release installed by pacman is on 1.19.3-3

### ISSUE THREAD

**Issue by ewirch** [manjaro/packages-extra#118]
Please update the Github repo.

**Comment by Ste74** [comment]
This is a our backup copy , not used in our repo , ver 1.19.3-3 is a arch pkg .. please check the packager ;)

**Comment by ewirch** [comment]
How do I know which repo the packages comes from?

**Comment by Ste74** [comment]
I don't know what de you use ; pamac or octopi have an option for see the details of the pkgs otherwise you can use pacman and do this

> pacman -Qi pkg-name 

to print the details.. if the packager contain adress to @manjaro.org is a our pkgs

**Comment by ewirch** [comment]
Ok, thanks.
