### ISSUE TITLE
GPL3 VIOLATION

### ISSUE THREAD

**Issue by Elrondo46** [manjaro/packages-extra#119]
source=(#"pamac-$pkgver-$pkgrel.tar.gz::https://github.com/manjaro/pamac/archive/v$_pkgver.tar.gz"
        pamac-$_pkgver.tar.xz)

The sources are not public for pamac 6 DEV. This is a violation of the GPL3 rules.

**Comment by guinux** [comment]
I will push sources tomorrow.

**Comment by Elrondo46** [comment]
Thank you very much for the open source philosophy

**Comment by guinux** [comment]
done:
https://github.com/manjaro/pamac/commit/80ea4ea70f95f0170083fff00ab4480fa62e2cd9
