### ISSUE TITLE
Question about Gnome and Manjaro Wallpapers

### ISSUE THREAD

**Issue by ryanvade** [manjaro/packages-extra#12]
Hello.  I am wondering how GNOME is adding these wallpapers (manjaro-artwork) to the Backgrounds menu.  I don't quite understand.  Is it just because the files are placed in /usr/share/backgrounds or is GNOME in the manjaro repositories patched to work with the manjaro-artwork package?

**Comment by philmmanjaro** [comment]
Please take a look at our [gnome profile](https://github.com/manjaro/manjaro-tools-iso-profiles/tree/master/gnome). Most stuff get configured via our overlay.
