### ISSUE TITLE
obmenu-generator is now v0.80 in AUR

### ISSUE THREAD

**Issue by fhdk** [manjaro/packages-extra#121]
@oberon2007 - https://aur.archlinux.org/packages/obmenu-generator/
The version in the repo is an old version compared to the present. The upstream menu format has been changed so an error is thrown

    Invalid option or value: keep_empty_categories at /usr/share/perl5/vendor_perl/Linux/DesktopFiles.pm line 100.

And the generated menu is invalid so I think it merits a rebuild of the package. What do you think?

**Comment by oberon2007** [comment]
Would you like to use it in a openbox profile? Or is it used in any other editions? In that case sure, let's update it! 👍

**Comment by fhdk** [comment]
That is exactly what I would like to do.

Does a package list or an iso profile exist for the latest Openbox edition?
https://sourceforge.net/projects/manjarolinux-community/files/openbox/archive/2015.07/

**Comment by oberon2007** [comment]
Will update the package then. There is no current ob-edition. Feel free to add it in the iso-profiles repo and adjust desktop-settings repo so we can create an updated settings-package!

**Comment by oberon2007** [comment]
Moved the package to community repo and updated.
