### ISSUE TITLE
[plymouth] Outdated packages

### ISSUE THREAD

**Issue by Vincent43** [manjaro/packages-extra#130]
Hi!

Plymouth packages are outdated as 0.9.3 version was released in  2017-08-09 and is avalaible in AUR https://aur.archlinux.org/packages/plymouth

Also currently there are 3 different plymouth packages (vanillia, dev and legacy). I think it would be nice to cleanup this and keep only the latest stable release.

**Comment by Ste74** [comment]
We have dropped support for plymouth some time ago.. for not confusing people better if we remove plymouth binary package from our repo. We can maintain in our repo the themes.. 
@philmmamjaro tought? Geen light to remove plymouth from our repo ?

**Comment by Vincent43** [comment]
I agree that removing them will be better than current state.

**Comment by Ste74** [comment]
Removed : https://github.com/manjaro/packages-extra/commit/c836d652047e0266edcff35a62bec358e5107528
For the problem of manjaro versioning we can explain on announce tread .

**Comment by Vincent43** [comment]
Thanks. There are a bunch of plymouth themes in repos. I guess they can be deleted too.

**Comment by Ste74** [comment]
If the themes are always supported why? Otherwise yes.. we don't use anymore plymouth so we can't confirm this.. this themes are branded for Manjaro so are specifically build for Manjaro :)

**Comment by Vincent43** [comment]
Supported themes for unsupported package...it can create confusion. IMHO it's better to move them to AUR if their authors care.
