### ISSUE TITLE
[go] outdated

### ISSUE THREAD

**Issue by abhigupta912** [manjaro/packages-extra#132]
Posting here because package manager indicates go is in extra repository.

The [go](https://golang.org/) package in manjaro is outdated.
Archlinux has the [updated package](https://www.archlinux.org/packages/extra/x86_64/go/)

> go1.9.2 (released 2017/10/25) includes fixes to the compiler, linker, runtime, documentation, go command, and the crypto/x509, database/sql, log, and net/smtp packages. It includes a fix to a bug introduced in Go 1.9.1 that broke go get of non-Git repositories under certain conditions.

**Comment by philmmanjaro** [comment]
See **testing** or **unstable** branch. On **stable** we may have a delay on the current packages from Arch.
