### ISSUE TITLE
[linux414-extramodules] [i686] Modules don't build, "No rule to make target 'arch/x86/Makefile_32.cpu'"

### ISSUE THREAD

**Issue by jonathonf** [manjaro/packages-extra#137]
Not sure where this `Makefile_32.cpu` should originate?

```
==> Starting build()...
make -C /lib/modules/4.14.2-1-MANJARO/build M=/build/src/acpi_call-1.1.0 modules
make[1]: Entering directory '/usr/lib/modules/4.14.2-1-MANJARO/build'
arch/x86/Makefile:90: arch/x86/Makefile_32.cpu: No such file or directory
make[1]: *** No rule to make target 'arch/x86/Makefile_32.cpu'.  Stop.
make[1]: Leaving directory '/usr/lib/modules/4.14.2-1-MANJARO/build'
make: *** [Makefile:8: default] Error 2
```

**Comment by philmmanjaro** [comment]
With **linux414** Arch only support x86_64 from their end. I've to check if I still had missed some for **i686**.

**Comment by philmmanjaro** [comment]
See also https://github.com/manjaro/packages-core/commit/9036068e2ffacb587bdf0ad27278a4081ee269b4#diff-3e7f2db70a77ce49dc71dae9658f96a6L307

**Comment by philmmanjaro** [comment]
A dirty fix would be to copy the **Makefile_32.cpu** to `/usr/lib/modules/4.14.2-1-MANJARO/build/arch/x86/Makefile_32.cpu`

**Comment by jonathonf** [comment]
Ah, interesting. The kernel itself builds so we _could_ patch that back in. Are you willing to maintain 32-bit config alongside 64-bit? I'm happy to keep building in either case.

**Comment by philmmanjaro** [comment]
@jonathonf: I can still maintaining the 32-bit config if you want. About packaging we have to create a build-server or some to make it automatically. `Makefile_32.cpu` will be part when you had rebuild the headers. This can be also done with next release. For now it is enough to have it on the wanted place in chroot or local PC to be able to build the extramodules.

**Comment by jonathonf** [comment]
For the short-term my build container will do the job; it means I can easily control the build order so extramodules get built against the correct kernel versions etc. A build server is worth looking into, though.
