### ISSUE TITLE
local-repo problem

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-extra#14]
local-repo.db is recognized during installation of root- and i3-Overlay-images but then I get ```"error: failed retrieving file 'local-repo.db' from disk : Couldn't open file /home/bernhard/local-repo/local-repo.db"```
see: http://pastebin.com/u17DTyfh

**Comment by oberon2007** [comment]
Same problem even when no local-repo packages are added. local-repo in pacman-default.conf alone will result in the described error.

**Comment by oberon2007** [comment]
trying now with added '$repo/$arch' to local-repo Server address. Will report back

**Comment by Kirek** [comment]
This is because it runs pacman inside the chroot, so it doesn't find the local repo. I will fix this later tonight.

**Comment by philmmanjaro** [comment]
This is really wrongly placed here. It needs to be added to **manjaro-tools**. Nothing to do with packaging in [extra].
