### ISSUE TITLE
nvidia-utils > mhwd-nvidia is missing PCIID: 1b82 Nvidia Gforce 1070 Ti

### ISSUE THREAD

**Issue by whollaus** [manjaro/packages-extra#143]
The LiveCD does not boot when the non-free driver is selected. The grafic card (ASUS ROG-STRIX-GTX1070TI) is not listed in /var/lib/mhwd/ids/pci/nvidia.ids.

More information:
https://forum.manjaro.org/t/manjaro-kde-installation-klappt-nicht-driver-nonfree/37773/7

**Comment by philmmanjaro** [comment]
That **v384** driver series doesn't support this card. You need [v387.22](https://devtalk.nvidia.com/default/topic/1025794/unix-graphics-announcements-and-news/linux-solaris-and-freebsd-driver-387-22/).
