### ISSUE TITLE
[nvidia-340] 340.106 is out with PTI compatiblity fix

### ISSUE THREAD

**Issue by jonathonf** [manjaro/packages-extra#144]
http://www.nvidia.com/Download/driverResults.aspx/130042/en-us:

> Fixed a compatibility problem between the nvidia.ko's Page Attribute Table (PAT) support and the kernel Page Table Isolation (PTI) patches.

There are kernel-specific patches in the various kernel extramodule dirs so I'm not sure what, if anything, needs to be changed with the packaging.

**Comment by philmmanjaro** [comment]
Normally only versioning needs to be bumped. I planned to update it by the end of the weekend. If you like you may go ahead. **v304** series, however seems to be dropped by Nvidia anyway ...

**Comment by jonathonf** [comment]
https://github.com/manjaro/packages-extra/commit/f57222d66f653d345f36d224eb2bd6aa83c85ebe

I'll kick off some builds.

**Comment by jonathonf** [comment]
Failing with kernel 4.14 (x86_64):

```
patching file uvm/nvidia_uvm_linux.h
Hunk #1 succeeded at 375 (offset 13 lines).
patching file uvm/nvidia_uvm_lite.c
Hunk #1 succeeded at 818 with fuzz 2.
patching file nv-drm.c
Hunk #1 FAILED at 173.
Hunk #2 FAILED at 183.
2 out of 2 hunks FAILED -- saving rejects to file nv-drm.c.rej
```
```
--- nv-drm.c    2017-09-15 01:16:51.000000000 +0200
+++ nv-drm.c    2017-11-19 00:51:45.006654148 +0100
@@ -173,8 +173,12 @@
 {
     int ret = 0;
 #if defined(NV_DRM_AVAILABLE)
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(4, 14, 0)
+    ret = drm_legacy_pci_init(&nv_drm_driver, pci_driver);
+#else
     ret = drm_pci_init(&nv_drm_driver, pci_driver);
 #endif
+#endif
     return ret;
 }

@@ -183,8 +187,12 @@
 )
 {
 #if defined(NV_DRM_AVAILABLE)
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(4, 14, 0)
+    drm_legacy_pci_exit(&nv_drm_driver, pci_driver);
+#else
     drm_pci_exit(&nv_drm_driver, pci_driver);
 #endif
+#endif
 }

 RM_STATUS NV_API_CALL nv_alloc_os_descriptor_handle(
```

**Comment by jonathonf** [comment]
Removing the 4.14 and 4.15 patches allows the module to compile... not sure what (if any) other functionality they include?

**Comment by philmmanjaro** [comment]
It will fail on **x86_64** ...

**Comment by jonathonf** [comment]
I've uploaded the packages to **unstable** so they can be tested by whoever is lucky enough to be running 340... :)

**Comment by jonathonf** [comment]
Oup, just seen your commit... rebuilding.

**Comment by philmmanjaro** [comment]
I was not able to build it on AMD Ryzen. Maybe Intel handles them differently ...

**Comment by philmmanjaro** [comment]
Seems only **v4.11** is still needed. **v4.14** and **v4.15** patches can be removed after all.

**Comment by jonathonf** [comment]
Will they get in the way if left applied?

**Comment by philmmanjaro** [comment]
No, it just uses an older code.

**Comment by jonathonf** [comment]
OK, good. :)
