### ISSUE TITLE
NVIDIA long-term release 390.25 available

### ISSUE THREAD

**Issue by jonathonf** [manjaro/packages-extra#148]
Freshly released: http://www.nvidia.com/Download/driverResults.aspx/130646/en-us

Currently building locally to test.

**Comment by jonathonf** [comment]
They build and install fine, no obvious issues.

PKGBUILD files are [here](https://github.com/jonathonf/manjaro-nvidia/), I'll create a PR to this repo tomorrow.

**Comment by philmmanjaro** [comment]
Will check the PR when ready.

**Comment by jonathonf** [comment]
PR for -extra: https://github.com/manjaro/packages-extra/pull/149
