### ISSUE TITLE
Firefox won't start 

### ISSUE THREAD

**Issue by kouros17** [manjaro/packages-extra#152]
After the update of **libvpx** to **1.7.0-1** firefox **58.0.1-1** doesn't launch:
```
╰─ firefox
XPCOMGlueLoad error for file /usr/lib/firefox/libxul.so:
libvpx.so.4: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
```
Firefox **58.0.1-2** from arch repos  works perfectly.

https://forum.manjaro.org/t/firefox-wont-start-unstable/39921

**Comment by philmmanjaro** [comment]
We have to repack ours ...

**Comment by philmmanjaro** [comment]
https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20180205/014721.html

**Comment by Ste74** [comment]
@philmmanjaro we repack only for distribution.ini file problems? I can write a hook to prevent this and return at arch upstream pkg if yes ...

**Comment by kouros17** [comment]
Updated to **58.0.2-1** in arch.

**Comment by philmmanjaro** [comment]
https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20180205/014731.html

**Comment by Ste74** [comment]
With this we can remove overlay for firefox
 https://github.com/manjaro/packages-community/commit/2aacf3acac1174d0f28b4d7cfcebc2bad70e5a3d
