### ISSUE TITLE
Consider xfce4-panel-compiz in the official repo

### ISSUE THREAD

**Issue by Cyspy** [manjaro/packages-extra#156]
Since compiz uses viewports rather than desktops,  xfce4-panel won't work fine with it, which makes the workspace indicator size wrong,  an package in AUR: [xfce4-panel-compiz](https://aur.archlinux.org/packages/xfce4-panel-compiz/)  fixes this problem. Maybe consider putting this package in the official repo?

**Comment by oberon2007** [comment]
Seems to make sense, since we also maintain **compiz-manjaro**. Maybe also add it there as an optdepends there? @philmmanjaro ?

**Comment by oberon2007** [comment]
Comments on the AUR suggest it's working nicely, also seems well-maintained.
I'll push it to unstable and we can people have at least test it for a while ...

**Comment by philmmanjaro** [comment]
Fine with me, go ahead.
