### ISSUE TITLE
bootsplash themes require linux414

### ISSUE THREAD

**Issue by NuLogicSystems** [manjaro/packages-extra#158]
I only have linux415 installed and trying to install the bootsplash themes always results in pacman wanting to install linux414 with it. Something is definitely off with the depends for these packages.
![shot-2018-04-19_04-40-33](https://user-images.githubusercontent.com/10186587/38980861-ee5e112a-438b-11e8-9316-44cdcd749e9f.jpg)

**Comment by oberon2007** [comment]
The bootsplash-themes currently explicitly depend on **linux414**, I guess this should be updated to **linux**

**Comment by oberon2007** [comment]
This has been fixed already in https://github.com/manjaro/packages-extra/commit/10bf3a4f655d419ef2e136f61e71c6f6e9f3983c#diff-6579d738d1b2f307e0ac0e4c02f671ee
I'll forward the packages to testing/stable branches

**Comment by oberon2007** [comment]
Ah. I see this hasn't even been packaged with the latest updates... Are those pkgs ready, @philmmanjaro ?

**Comment by philmmanjaro** [comment]
They were on the server, but somehow boxit fugged it up ...

https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20180416/016157.html
