### ISSUE TITLE
There is no README.md file

### ISSUE THREAD

**Issue by TomaszGasior** [manjaro/packages-extra#167]
https://github.com/manjaro/packages-extra/blob/da50980aba79e32cf1a2d04ed91930ef0d1919e3/gtk3-classic/gtk3-classic.install#L11
here, it seems to me

**Comment by oberon-manjaro** [comment]
Haha, right!
NOW there is :wink:

**Comment by TomaszGasior** [comment]
Please wait, I will update package now.
