### ISSUE TITLE
xfce4-pulseaudio-plugin requires libwnck3 to work , but it’s not a dependency 

### ISSUE THREAD

**Issue by debianr2** [manjaro/packages-extra#170]

**Comment by ryanmusante** [comment]
Thank you!

**Comment by oberon-manjaro** [comment]
**libwnck3** is a dependency of **xfce4-panel**, therefor not needed here.

**Comment by debianr2** [comment]
No, xfce4-panel has libwnck as a dependency, not libwnck**3**.

**Comment by oberon-manjaro** [comment]
**xfce4-panel** has **libwnck**,
**xfce4-panel-gtk3** has **libwnck3**

**Comment by oberon-manjaro** [comment]
xfce4-pulseaudio-plugin is supposed to work with both the gtk2 and the gtk3 panel version ... so ... :wink:

**Comment by debianr2** [comment]
Well, without libwnck3 it doesn't.
`(process:3695): xfce4-panel-wrapper-CRITICAL **: 23:42:48.619: Wrapper pulseaudio-8: Failed to open plugin module "/usr/lib/xfce4/panel/plugins/libpulseaudio-plugin.so": libwnck-3.so.0: cannot open shared object file: No such file or directory.
xfce4-panel(external): pulseaudio-8: child exited with status 256`

**Comment by oberon-manjaro** [comment]
Hrm. now I get it. I must say that the information you originally provided was not very helpful.
The terminal output you are now showing tells more.
Our version of the plugin uses a newer snapshot, we should have made this a dedicated **-gtk3** package ...
Best solution for now will indeed be adding **libwnck3** to the plugin package and then remove the old **linwnck** dependency once we drop xfce4-gtk2 pkgs.

**Comment by oberon-manjaro** [comment]
Actually it isn't even the git commit, but the fact that we compiled it against **xfce4-gtk3** packages ... :wink:

**Comment by oberon-manjaro** [comment]
https://gitlab.manjaro.org/packages/extra/xfce4-pulsaudio-plugin/commit/673c3d17dd4293ab7df95c410a1aa7b22388e43c
