### ISSUE TITLE
system-config-printer missing in current manjaro-printer

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-extra#18]
Is there a reason why manjaro-printer has not been updated to 2015.06-2, yet?
rel 1 misses system-config-printer: https://forum.manjaro.org/index.php?topic=24613.msg212693#msg212693

**Comment by philmmanjaro** [comment]
Am 29.07.2015 um 23:48 schrieb Bernhard Landauer:
> Is there a reason why manjaro-printer has not been updated to 2015.06-2, yet?
> rel 1 misses system-config-printer: https://forum.manjaro.org/index.php?topic=24613.msg212693#msg212693
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/manjaro/packages-extra/issues/18
> 

Ist einfach untergegangen ...

**Comment by oberon2007** [comment]
:)
