### ISSUE TITLE
[pa-applet]

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-extra#28]
Should it not have depends=pulseaudio ?

**Comment by philmmanjaro** [comment]
configure says:
```
PKG_CHECK_MODULES([GLIB], [glib-2.0])
PKG_CHECK_MODULES([GTK3], [gtk+-3.0])
PKG_CHECK_MODULES([LIBPULSE], [libpulse])
PKG_CHECK_MODULES([LIBPULSE_GLIB], [libpulse-mainloop-glib])
PKG_CHECK_MODULES([LIBNOTIFY], [libnotify])
PKG_CHECK_MODULES([XLIB], [x11])
```

**Comment by oberon2007** [comment]
But it does not pull in pulseaudio and is unusable without it...
I installed it yesterday and forgot to install pulse, too :blush:

**Comment by oberon2007** [comment]
Pulseaudio needs to be autostarted before pa-applet. So if the package is not present is will not work.

**Comment by philmmanjaro** [comment]
Ok, point taken. Will update it.
