### ISSUE TITLE
[kpmcore] produces filesystem conflicts

### ISSUE THREAD

**Issue by udeved** [manjaro/packages-extra#29]
The kde-minimal profile doesn't build, specifically the livecd image.

~~~
error: failed to commit transaction (conflicting files)
kpmcore: /build/manjaro-tools/buildiso/kde-minimal/x86_64/livecd-image/usr/lib/qt/plugins/libpmdummybackendplugin.so exists in filesystem
kpmcore: /build/manjaro-tools/buildiso/kde-minimal/x86_64/livecd-image/usr/lib/qt/plugins/libpmlibpartedbackendplugin.so exists in filesystem
kpmcore: /build/manjaro-tools/buildiso/kde-minimal/x86_64/livecd-image/usr/share/kservices5/pmdummybackendplugin.desktop exists in filesystem
kpmcore: /build/manjaro-tools/buildiso/kde-minimal/x86_64/livecd-image/usr/share/kservices5/pmlibpartedbackendplugin.desktop exists in filesystem
kpmcore: /build/manjaro-tools/buildiso/kde-minimal/x86_64/livecd-image/usr/share/kservicetypes5/pmcorebackendplugin.desktop exists in filesystem
Errors occurred, no packages were upgraded.
~~~

**Comment by philmmanjaro** [comment]
**kpmcore** is just for **calamares-dev**. last time I built it it was fine.

**Comment by udeved** [comment]
a build from stable with kde-minimal fails.

**Comment by philmmanjaro** [comment]
Please check why **kpmcore** gets installed and post a full build-log if possible.

**Comment by udeved** [comment]
I guess its caused by the partitionmanager package in the desktop list.
I haven't kept track on kde profile, needs to be removed..

**Comment by philmmanjaro** [comment]
No. **kpmcore** is only needed if you try the dev build of **calamares**. So check which packages get installed and why.

**Comment by udeved** [comment]
Builds fine with partitionmanager removed.

**Comment by philmmanjaro** [comment]
Still check by which package it is needed ...

**Comment by udeved** [comment]
partitionmanager

**Comment by Kirek** [comment]
My guess is that partitionmanager moved some of its stuff to kpmcore, so that's why we have this conflict. It needs to be updated to the recently tagged 1.9.50 (which has kpmcore as dependency).
https://quickgit.kde.org/?p=partitionmanager.git

**Comment by philmmanjaro** [comment]
maybe for the git version, but not for the current stable:
```
[phil@manjaro ~]$ sudo pacman -S partitionmanager
resolving dependencies...
:: There are 2 providers available for phonon-qt5-backend:
:: Repository extra
   1) phonon-qt5-gstreamer  2) phonon-qt5-vlc

Enter a number (default=1): 
looking for conflicting packages...

Packages (39) attica-qt5-5.14.0-1  gamin-0.1.10-8  gpgmepp-15.08.1-1
              karchive-5.14.0-1  kauth-5.14.0-1  kbookmarks-5.14.0-1
              kcodecs-5.14.0-1  kcompletion-5.14.0-1  kconfig-5.14.0-1
              kconfigwidgets-5.14.0-1  kcoreaddons-5.14.0-1  kcrash-5.14.0-1
              kdbusaddons-5.14.0-1  kglobalaccel-5.14.0-1  kguiaddons-5.14.0-1
              ki18n-5.14.0-1  kiconthemes-5.14.0-1  kio-5.14.0-1
              kitemviews-5.14.0-1  kjobwidgets-5.14.0-1
              knotifications-5.14.0-1  kservice-5.14.3-1  ktextwidgets-5.14.0-1
              kwallet-5.14.0-1  kwidgetsaddons-5.14.0-1  kwindowsystem-5.14.0-1
              kxmlgui-5.14.0-1  libdbusmenu-qt5-0.9.3+15.10.20150604-1
              media-player-info-22-1  phonon-qt5-4.8.3-2
              phonon-qt5-gstreamer-4.8.2-1  polkit-qt5-0.112.0-1
              qt5-declarative-5.5.0-2  qt5-script-5.5.0-2
              qt5-x11extras-5.5.0-2  qt5-xmlpatterns-5.5.0-2  solid-5.14.0-1
              sonnet-5.14.0-1  partitionmanager-1.2.1-1

Total Download Size:    19.92 MiB
Total Installed Size:  105.27 MiB

:: Proceed with installation? [Y/n] n
```

@udeved: always post the version and the build-log so we can properly track this one down. As I see it, it's just some **AUR** package ...

**Comment by philmmanjaro** [comment]
@udeved: with **partitionmanager** it conflicts. Only the git version depends on it. So which package needs **kpmcore** on your install media?

**Comment by udeved** [comment]
I have no clue, you better ask kirek about that.
I just removed partitionmanager from Packages-kde-minimal and the build is ok.
On gentoo, partitionmanager depends on kpmcore iirc.

~~~
## Applications
dolphin
konsole
kate
qpdfview
qupzilla
kwrite
octopi
#partitionmanager
#manjaro-settings-manager
kcm-msm
manjaro-welcome
~~~

If I remove the comment, the build fails.
All the rest of the lists are symlinks to shared.
My lxqt did build fine, so its no problem in Packages-Livecd

**Comment by philmmanjaro** [comment]
I found the issue within **calamares** package. This is now fixed.
