### ISSUE TITLE
[xfdesktop] Add a shadow to the desktop icon text

### ISSUE THREAD

**Issue by Photon89** [manjaro/packages-extra#33]
When changing the default wallpaper to a light one, the white text in the desktop icon names becomes hard to read. There is a possibility to add a shadow to make it better readable by adding some options into .gtkrc-2.0, see here: http://docs.xfce.org/xfce/xfdesktop/advanced I'd propose something like:

    XfdesktopIconView::shadow-x-offset = 1
    XfdesktopIconView::shadow-y-offset = 1
    XfdesktopIconView::shadow-color = "#000000"

Here is how it looks like:

Current situation: ![auswahl_09-11-2015_19 29 36](https://cloud.githubusercontent.com/assets/1191480/11062091/492b039a-87ac-11e5-9624-6f6f1750fc55.png) With shadow: ![auswahl_09-11-2015_19 30 37](https://cloud.githubusercontent.com/assets/1191480/11062093/4c9a50bc-87ac-11e5-9b06-e489f5832a8a.png)

**Comment by alexandruianu** [comment]
Your dropbox links aren't working

**Comment by Photon89** [comment]
Thanks! I now uploaded the pictures directly.

**Comment by philmmanjaro** [comment]
Is it more a **theme** think or general **skel** topic for our **manjaro-tools iso-profiles**?

**Comment by Photon89** [comment]
I guess, it's a skel topic, those settings are afaik not theme specific. I think, one should put this into /etc/skel/.gtkrc-2.0 or something like that.

**Comment by udeved** [comment]
It seems toolkit specific, sounds like gtk2 stuff.

**Comment by Photon89** [comment]
Toolkit specific but not theme specific, I think.

**Comment by philmmanjaro** [comment]
Ok, I'll adopt it into our todays **15.12-pre2** release, which I'll upload later.

**Comment by Photon89** [comment]
Great, thanks!

**Comment by philmmanjaro** [comment]
After second thought we don't have this issue with the given theme we ship by default. Sure other themes than **menda** might need adjustments. This is not the case for that theme:
![menda](https://cloud.githubusercontent.com/assets/5050022/11099167/1dcd0e2e-88aa-11e5-99cb-7ede42380ed0.jpg)

**Comment by Photon89** [comment]
I think, the problem is not the icon theme or GTK theme but the wallpaper. A change of wallpaper, however, is a quite frequent thing and it would be good if the usability is not affected by it.

**Comment by philmmanjaro** [comment]
![15 12-pre2-menda](https://cloud.githubusercontent.com/assets/5050022/11103141/f7961e96-88c0-11e5-999b-b249857f7bc8.jpg)

There is no problem. Even with white backgrounds. This screenshot shows the standard **menda** thema we use by default. Your screenshot shows a different theme which might extra adjustments. Nothing to do with our release, though.

**Comment by Photon89** [comment]
Very interesting! I'm running an up to date Manjaro install with default GTK theme (Adwaita-Manajro, I think) and icon theme changed to Faenza and have the problem illustrated in the bug report, that is, no greyish border around the characters. Menda isn't even in the list of available icon themes (the system has been set up when Faenza Green has been used as default icon theme). But I think, that the icon theme isn't the reason for the way how the characters are displayed. But then, what is the reason?

**Comment by philmmanjaro** [comment]
Please install the **menda** theme and your issue is solved:
`sudo pacman -S menda-themes menda-circle-icon-theme xcursor-menda`
Faenza might have an issue. I assume you use the **XFCE Edition**.

**Comment by Photon89** [comment]
Thanks, changing the GTK theme to Menda solved the problem for me!
