### ISSUE TITLE
[mdm] fails to start after Manjaro Update 2015-11-23 (stable)

### ISSUE THREAD

**Issue by skulltus** [manjaro/packages-extra#34]
By reading the output of journalctl -xru mdm :
Nov 24 15:16:59 john-pc systemd[1]: mdm.service: Service hold-off time over, scheduling restart.
Nov 24 15:16:57 john-pc systemd[1]: mdm.service: Failed with result 'exit-code'.
Nov 24 15:16:57 john-pc systemd[1]: mdm.service: Unit entered failed state.
Nov 24 15:16:57 john-pc systemd[1]: mdm.service: Control process exited, code=exited status=1
Nov 24 15:16:57 john-pc mdm-stop[1059]: /var/run/mdm.pid doesn't exist, perhaps MDM isn't running
Nov 24 15:16:57 john-pc systemd[1]: mdm.service: Main process exited, code=exited, status=127/n/a
Nov 24 15:16:57 john-pc mdm[1056]: /usr/bin/mdm-binary: error while loading shared libraries: libwrap.so.0: cannot open shared object file: No such file or directory
Nov 24 15:16:57 john-pc systemd[1]: Started Linux Mint Display Manager.
-- Subject: Unit mdm.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit mdm.service has finished starting up.
-- 
-- The start-up result is done.

you can see that libwrap.so is missing. The interesting part is that this lib is part of the tcp_wrappers package which is part of the base group and for some reason it wasn't installed as part of the base group on my system (Manjaro XFCE). Also mdm 2.0.4 version was running without installing tcp_wrappers. By looking at the PKGBUILD for mdm in github i've noticed that tcp_wrappers is not listed as a dependency. I think that the option that configures mdm to use libwrap is --enable-secureremote=yes. But I didn't test building the package with --enable-secureremote=no. I've also noticed that --enable-ipv6=yes option is listed twice, so you might want to fix that as well. Manually installing tcp_wrappers fixes the issue I'm reporting.

**Comment by philmmanjaro** [comment]
**mdm 2.0.7** should fix this.
