### ISSUE TITLE
Have a plasma5-ssh-agent package?

### ISSUE THREAD

**Issue by udeved** [manjaro/packages-extra#41]
Since arch removed kde-agents package, kde users are left to set up ssh agent on their own.

Should we have a package, that provides ssh-agent startup and shutdown scripts?

/etc/xdg/plasma-workspace/env/ssh-agent-startup.sh
~~~
#!/bin/sh
[ -n "$SSH_AGENT_PID" ] || eval "$(ssh-agent -s)"
~~~

/etc/xdg/plasma-workspace/shutdown/ssh-agent-shutdown.sh
~~~
#!/bin/sh
[ -z "$SSH_AGENT_PID" ] || eval "$(ssh-agent -k)"
~~~

**Comment by philmmanjaro** [comment]
why not.

**Comment by udeved** [comment]
Should I build it and push to unstable?
date as version is fine?

**Comment by philmmanjaro** [comment]
Is it more used for KDE apps or Plasma? I'd recommend to use their versions then.

**Comment by udeved** [comment]
Ok, will use 5.5.1 then.
Its for plasma I think, plasma-workspace is depend, and openssh.
It activates ssh-agent in plasma session.

**Comment by philmmanjaro** [comment]
Fine with me. Maybe **v5.5** or so, since I don't expect to have point-releases there ...

**Comment by udeved** [comment]
Not sure if kwallet is supposed to fill this task, but it doesn't work well atm I think.
Ie we might drop this package at some point.

**Comment by philmmanjaro** [comment]
Jupp, if not needed anymore we can drop it.

**Comment by philmmanjaro** [comment]
Btw., is this issue not a little bit [older](https://bbs.archlinux.org/viewtopic.php?id=175148) ?!?

**Comment by udeved** [comment]
For the moment, I think it dramatically helps, from dolphin-plugins to konsole ssh.
On my system, kwallet somehow doesn't unlock like it used to on kde4.

Very much possible older issue, I took these scripts from my gentoo, when it still used early kf5/plasma5 live builds, that were more stable than masked releases.

**Comment by philmmanjaro** [comment]
Ah great, makes sense. Using [kwallet is possible](https://wiki.archlinux.org/index.php/KDE_Wallet#Using_the_KDE_Wallet_to_store_ssh_keys), but not so easy to setup for beginners ...

**Comment by udeved** [comment]
We can print a msg, thatr user has just to run
ssh-add

to add default key for the session, ie no more sshaskpass

**Comment by philmmanjaro** [comment]
sure, add it to the install script. Maybe add some msg() function to it, so it is more readable ...

**Comment by udeved** [comment]
Regarding msg, its why I thought, we could use the msg functions from util-msg.sh and make them somehow available systemwide.

**Comment by philmmanjaro** [comment]
That would make also sense. For now I'm also fine to add it to the install scripts one by one until we have a global solution for it ...

**Comment by udeved** [comment]
No problem, just reminded me, that it'd be probably cool to have msg functions available without sourcing them manjaro-tools "namespace"
