### ISSUE TITLE
[liblouis] overlay still needed?

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-extra#43]
I see that the newest archlinux version **2.6.5-1** now has ``--disable-static`` like our overlay.
The only difference still is ``--enable-ucs4``
Do we still need the overlay pkg? @Kirek , @coffeeking ?

**Comment by Kirek** [comment]
Yes, we still need it, the whole reason we have this package is because --enable-ucs4 https://github.com/manjaro/packages-extra/commit/0e041fca84ca50a9ccd2742293baeb63c9908086
