### ISSUE TITLE
Kirek will you rebuild plasma-menda-next please

### ISSUE THREAD

**Issue by anexation** [manjaro/packages-extra#5]
Kirek, I updated the menda and menda-kde4 stuff to get it in sync wth upsream changes so when you have time will you please update... thx

added make depends was looking for KDecoration2Config.cmake
https://aur.archlinux.org/packages/kdecoration-git/

**Comment by Kirek** [comment]
@anexation 
So with plasma 5.2 I want to update menda-plasma, Its the current state of the repo https://github.com/anexation/menda-plasma-next ok?

**Comment by anexation** [comment]
yes i just updated it and its what i included in the pre2 iso i just uploaded. the version numbers i made are like.

menda-20150127-1-x86_64.pkg.tar.xz

**Comment by anexation** [comment]
can you make the version number the exact same?

**Comment by Kirek** [comment]
Yes, I will

**Comment by anexation** [comment]
k thank you kirek
