### ISSUE TITLE
new iso-profiles pkgs should conflict/replace old [manjaro-iso-profiles]

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-extra#50]
https://forum.manjaro.org/index.php?topic=31109.msg256621#msg256621

**Comment by philmmanjaro** [comment]
I think at least base should do that.

**Comment by Kirek** [comment]
Is this fixed yet?

**Comment by Ste74** [comment]
I have notice no.. an italian user want install the new desktop setting but not replace the old.. manually have to delete the skel folder.

**Comment by udeved** [comment]
Would be yet another case to do this with a pacman hook pre transaction.
I dunno, no decision or feedback on hooks so far.

**Comment by oberon2007** [comment]
hook to remove **/etc/skel** I think is a beautiful elegant idea!

**Comment by udeved** [comment]
Replacing manjaro-system with hooks is also a beautiful idea, I think.
