### ISSUE TITLE
[Calamares] new additional dependencies

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-extra#54]
Clamares' new dependencies will result in a [significant increase in ISO size](https://forum.manjaro.org/index.php?topic=31499.msg258858#msg258858). I wonder if there could be any way around it. Would maybe a trimmed down version of **kpmcore** providing just the necessary for Calamares be an option?

**Comment by oberon2007** [comment]
**kpmcore** depends on **kio** which
```
Depends On      : solid  karchive  kjobwidgets  kbookmarks  libxslt
                  kwallet  desktop-file-utils
```

**Comment by philmmanjaro** [comment]
No.

**Comment by oberon2007** [comment]
:stuck_out_tongue_closed_eyes:

**Comment by udeved** [comment]
I you have some time left, you could try to strip the framework libraries.
Likely, a weekend is not enough Bernhard. :tongue:

**Comment by oberon2007** [comment]
:+1:

**Comment by philmmanjaro** [comment]
What is the actual problem here. We switched over in **Calamares** to use more framework packages. **kpmcore** is the base also used by **partitionmanager** now. We can check with **KDE** and **Blue Systems** if there are some options to strip some, however this is now the way it is and works. How much extra size we are actually talking about?

**Comment by udeved** [comment]
Iguess it depends purely on the target DE you put on iso.
For me, its thus that brings the extra weight.

**Comment by oberon2007** [comment]
Well, to install clamares 2.0 on my running system (i3 plus Cinnamon are installed) means a total download of **85MB**. Difficult to say what the difference is between an ISO with Thus and Calamares, or between Calamares 1.1.4.2 and 2.0 ...

**Comment by oberon2007** [comment]
I have some qt-applications installed aswell btw

**Comment by udeved** [comment]
If its qt4 apps, its extra weight too. frameworks are qt5 based.

**Comment by oberon2007** [comment]
```
Packages (39) attica-qt5-5.19.0-1  gamin-0.1.10-8  gpgmepp-15.12.2-1
              gptfdisk-1.0.1-2  karchive-5.19.0-1  kauth-5.19.0-1
              kbookmarks-5.19.0-1  kcodecs-5.19.0-1  kcompletion-5.19.0-1
              kconfig-5.19.0-1  kconfigwidgets-5.19.0-1
              kcoreaddons-5.19.0-1  kcrash-5.19.0-1  kdbusaddons-5.19.0-1
              kglobalaccel-5.19.0-1  kguiaddons-5.19.0-1  ki18n-5.19.0-1
              kiconthemes-5.19.0-1  kio-5.19.0-1  kitemviews-5.19.0-1
              kjobwidgets-5.19.0-1  knotifications-5.19.0-1
              kpmcore-2.0.1-1  kservice-5.19.0-1  ktextwidgets-5.19.0-1
              kwallet-5.19.0-1  kwidgetsaddons-5.19.0-1
              kwindowsystem-5.19.0-1  kxmlgui-5.19.0-1
              libdbusmenu-qt5-0.9.3+15.10.20150604-3
              media-player-info-22-1  phonon-qt5-4.8.3-5
              phonon-qt5-gstreamer-4.8.2-4  polkit-qt5-0.112.0-3
              qt5-script-5.5.1-9  solid-5.19.0-1  sonnet-5.19.0-1
              yaml-cpp-0.5.3-1  calamares-2.0-1

Total Installed Size:  84.81 MiB
```

**Comment by philmmanjaro** [comment]
Well, **thus** is normally bigger than **calamares** in dependencies. We actually have to check that. However **calamares 2.0** and future versions of the installer will be the way we go. We also work closely with **KDE** and **Blue Systems** together, to get it work.

**Comment by philmmanjaro** [comment]
Please remove the **live-image** folder and its **build.make_image_live** file, edit **Packages-Live** to install only one **installer** and rebuild your ISO with the **-c** switch. Repeat that step with the other installer to see which installer will be larger that the other to discuss this further.

**Comment by oberon2007** [comment]
ok. will investigate.

**Comment by oberon2007** [comment]
So, the result surprised me a bit ;)
I tried with Deepin and Xfce:
![installers](https://cloud.githubusercontent.com/assets/11800714/13366088/5d9a1c76-dcd9-11e5-9164-cd0a588ad5ba.png)

**Comment by philmmanjaro** [comment]
**Calamares** is designed in mind of **KDE**. Other editions are more in the view of **GTK**. So this means that **Thus** would be more suitable for **XFCE** and **Calamares** more for **QT5** based editions.

**Comment by oberon2007** [comment]
Yes. Actually I am surprised about how little the difference in resulting ISO size between Thus or Calamares turned out in these experiments. And I don't understand yet why that upgrade from Calamares 1 to 2 series on Cinnamon seemed to have such an impact...

**Comment by Kirek** [comment]
It was 84.81 MB uncompressed, just look at kio, https://www.archlinux.org/packages/extra/x86_64/kio/ the compression ratio is 6:1, so the real overhead in the uses is likely around 10-15 MB extra

**Comment by oberon2007** [comment]
good point! :)

**Comment by Chrysostomus** [comment]
For bspwm edition, addition is about twice that. But nothing can nor should be done about that.
