### ISSUE TITLE
[pamac] libpamac.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-extra#55]
Is there maybe a typo somwhere in pamac source?
Is it supposed to look for **libpamc.so** actually by any chance?

**Comment by oberon2007** [comment]
Ah. no
https://github.com/manjaro/pamac/blob/84bd81d4178fa13a10096b4f5923b8a7e82a0074/Makefile#L28
Thing is, it doesn't get installed!

**Comment by philmmanjaro** [comment]
Seems to be my problem. I've to update the PKGBUILD.

**Comment by philmmanjaro** [comment]
Fixed with 1da57f78ece3ec1842eaa72544e62763424e7122
