### ISSUE TITLE
[manjaro-backgrounds]

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-extra#56]
@udeved we have that package [manjaro-backgrounds] that you seem to have packaged a while ago but I cannot find the PKGBUILD nor the repo anywhere... :wink: Does all that still exist? If yes could you point me in the right direction? thanks

**Comment by udeved** [comment]
Doesn't exist any longer. I packaged it just to get it off the git repo.

**Comment by oberon2007** [comment]
ok. no problem.

**Comment by udeved** [comment]
Best would be to tar backgrounds, upload to SF, and source it in PKGBUILD.

**Comment by oberon2007** [comment]
Yes. Sounds good. Lets do that when we have a nice up-to-date collection! ;)
