### ISSUE TITLE
[dkms] check why newer version doesn't work with spl/zfs

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/packages-extra#57]
- somehow newer dkms versions don't work with spl/zfs
- we have to check why

**Comment by philmmanjaro** [comment]
https://forum.manjaro.org/index.php?topic=31682.0

**Comment by philmmanjaro** [comment]
An option would be to backport the **pacman hooks** but keep the current version and patches until **dkms** gets released upstream in a newer version or spl/zfs has a fix.

**Comment by philmmanjaro** [comment]
https://github.com/manjaro/release-plan/issues/39

**Comment by ActualizeInMaterial** [comment]
I want to note that the current (old) `dkms` doesn't work with `aur/phc-intel` 0.3.2.12.21-1 because:

> fs4000 commented on 2016-02-27 11:16			 
> I have updated this package to use DKMS for automatically building the kernel module. This is possible > due to the new hooks feature of pacman which is used in the new DKMS package.
