### ISSUE TITLE
calamares: missing patch

### ISSUE THREAD

**Issue by Kirek** [manjaro/packages-extra#60]
prefer_budgie_before_gnome.patch file is missing, anyone knows what it exactly does? Or has the patch.

**Comment by Ste74** [comment]
I not sure if this is the problem but budgie is confused whit gnome session in manjaro tools . Philip and Marcus add in manjaro tools an array to specify the de during the building .

**Comment by udeved** [comment]
The DE is detected by buildiso.

The DEs are defined in a map file.
/usr/share/manjaro-tools/desktop.map

    lauchner:binary

Since it reads line by line, later entries take precedence.

**Comment by oberon2007** [comment]
Would it maybe make sense for some reason that Philip wanted to change the order of entries here?:
https://github.com/calamares/calamares/blob/262fdec3f34bb6d38aa04c09de42183b56897a4b/src/modules/displaymanager/main.py#L34
It's the only place where budgie appears in Calamares code in any case ...

**Comment by oberon2007** [comment]
Look! This commit: https://github.com/calamares/calamares/commit/8cbefa12e042ac85239b0312d4477cb21c241823

**Comment by oberon2007** [comment]
He reverted the commit afterward.

**Comment by Kirek** [comment]
Thanks! That's exactly what I was looking for.

**Comment by Kirek** [comment]
https://github.com/manjaro/packages-extra/commit/cf51ff8afb5de4cb9ebb2119785c4e4be7d66f6f

**Comment by oberon2007** [comment]
:coffee: :mag: :laughing:
