### ISSUE TITLE
poppler-based PDF viewers do not display CKJ characters out of the box.

### ISSUE THREAD

**Issue by crocket** [manjaro/packages-extra#61]
https://wiki.manjaro.org/index.php?title=About_Manjaro says manjaro is a user-friendly distribution. It also says _**For newcomers**, a user-friendly installer is provided, and the system itself is designed to work fully 'straight out of the box'_, so I think this issue is relevant.

poppler-based PDF viewers like evince, okular, and qpdfview do not display CKJ(Chinese, Korean, Japanese) characters out of the box because poppler-data is required for CKJ characters and is an optional dependency of poppler. I'm a linux veteran, and it took days of slow thinking to figure out that I had to install poppler-data.

If it takes days to diagnose why CKJ characters aren't displayed in PDF files, it's hard to say manjaro works fully out of the box for users who speak chinese, korean, or japanese.

I looked at manjaro language pack, and it seems it can't handle poppler out of the box. So, I thought of two ways.

1. You could probably add dummy packages like `poppler-ko`, `poppler-ja`, and `poppler-ch` to make the CKJ language packs install poppler-data on systems that have poppler installed.
2. A simpler way to resolve the issue is to make poppler-data a proper dependency of poppler. poppler-data consumes less than 13MB on my system.

**Comment by alexandruianu** [comment]
I think adding poppler data as a dependency is the better solution.

**Comment by Kirek** [comment]
Add poppler-data as dependency will mean maintaining that package... 
msm support language global language packages, so we can do that for poppler and poppler-data, also add poppler-data to the package profiles for the oficial editions.

**Comment by Kirek** [comment]
Done

msm
https://github.com/manjaro/manjaro-settings-manager/commit/cc4cb97aebfefab48a315d47566cd44d4b59c510
https://github.com/manjaro/manjaro-settings-manager/commit/306235df000c066509955e6a51a4c64d10e3015a

Profiles
https://github.com/manjaro/manjaro-tools-iso-profiles/commit/72bda87fdf245f4ed88174657fe8c54608697291

**Comment by crocket** [comment]
Thank you!!!

**Comment by wanghaisheng** [comment]
@crocket    hi  i have poppler-data  installed .but when i run 
```
pdftohtml -c -hidden -xml test.pdf test.xml
```
i could not  get correct chinese characters. do you know what cause this ?

you can get test file from 
link: https://pan.baidu.com/s/1dFiSrDn 
password: ai5u

**Comment by crocket** [comment]
@wanghaisheng I think you should ask the question on manjaro forum or some other linux forum like www.linuxquestions.org. I don't know much about this.

**Comment by wanghaisheng** [comment]
@crocket  thx
