### ISSUE TITLE
Update yaourt to 1.8.1

### ISSUE THREAD

**Issue by crocket** [manjaro/packages-extra#62]
https://github.com/archlinuxfr/yaourt/releases says it was released weeks ago.
I noticed the upgrade because the current version of yaourt(`1.7-2`) on manjaro fails to build `python-yapsy` from AUR. https://github.com/archlinuxfr/yaourt/issues/253

**Comment by oberon2007** [comment]
We'll have to find out why @philmmanjaro used an [explicit commit](https://github.com/manjaro/packages-extra/blob/master/yaourt/PKGBUILD#L18) for our package.
In any case I don't think that the yaourt version is the reason for your failed compilation.
Your posted error message says:
> makepkg: invalid option '--pkg'
option ``--pkg`` was dropped by makepkg a while ago! :stuck_out_tongue_winking_eye:

**Comment by oberon2007** [comment]
oh. now I get it. It's **yaourt** that is trying to use the old option... :laughing: :stuck_out_tongue_closed_eyes:

**Comment by oberon2007** [comment]
@crocket , is the **yaourt** version from AUR working for you?

**Comment by oberon2007** [comment]
I think what Philip did at that moment simply had to do with the timing of transition to pacman 5.0
I will update to package-query 1.8 and yaourt 1.8.1 and push it to unstable. Let's see what happens! ;)

**Comment by crocket** [comment]
@oberon2007 I'm late. yaourt from AUR worked for me.

**Comment by oberon2007** [comment]
No problem! ;) The new package in unstable will, too .. hopefully :laughing:
