### ISSUE TITLE
linux46-extramodules: broken nvidia and tp_smapi

### ISSUE THREAD

**Issue by Kirek** [manjaro/packages-extra#65]
**nvidia** 
build logs
[linux46-nvidia-1:352.79-0.1-i686-build.log.txt](https://github.com/manjaro/packages-extra/files/190858/linux46-nvidia-1.352.79-0.1-i686-build.log.txt)
[linux46-nvidia-1:352.79-0.1-x86_64-build.log.txt](https://github.com/manjaro/packages-extra/files/190859/linux46-nvidia-1.352.79-0.1-x86_64-build.log.txt)

**tp_smapi**
The kernel added 
KBUILD_CFLAGS   += $(call cc-option,-Werror=incompatible-pointer-types)
So a warning that was ignored, now it makes it fail.
[linux46-tp_smapi-0.41-0.1-x86_64-build.log.txt](https://github.com/manjaro/packages-extra/files/190860/linux46-tp_smapi-0.41-0.1-x86_64-build.log.txt)

Any idea how to fix those?

**Comment by FadeMind** [comment]
@Kirek @philmmanjaro 
https://devtalk.nvidia.com/default/topic/926824/linux/364-12-won-t-compile-against-latest-git-tree-patches-for-4-6-0-rc1-included-/

**Comment by Kirek** [comment]
I know this patches, a variation of the first one is needed for nvidia-340, but for 352 the build fails even after patching it.

**Comment by philmmanjaro** [comment]
No rush in fixing these. I might take a look on Saturday at it.

**Comment by philmmanjaro** [comment]
@Kirek: does the patch work for **361.42** release?

**Comment by Kirek** [comment]
For 361.42 you only need the first patch from the link provided by @FadeMind

**Comment by Kirek** [comment]
Well at least for 361.28 you only needed that one.

**Comment by philmmanjaro** [comment]
What about the second patch? Was this tested?

**Comment by Kirek** [comment]
The second one is only needed for 364, it you search "drm_mode_fb_cmd2" in the 361.x code you won't find anything.

**Comment by philmmanjaro** [comment]
Ah ok, for the **tp_smapi** issue please apply https://github.com/evgeni/tp_smapi/commit/8f40fcf3d9a4bfb9c3dae1caa2107ea3a367a609

**Comment by Kirek** [comment]
Ok, will build those two modules and push rc1

**Comment by Kirek** [comment]
361.28 doesn't need any patch

> // We used to return VM_FAULT_MINOR here. However, that was deprecated
        // in the kernel, and the new guideline is to return 0 in case of a
        // minor fault. The VM_FAULT_MINOR symbol itself was removed in
        // March, 2016 with commit 0e8fb9312fbaf1a687dd731b04d8ab3121c4ff5a.

**Comment by philmmanjaro** [comment]
@Kirek: if you on the **nvidia** driver, you can also adopt the **sum_arch** way to all other extramodules shipping nvidia. I was to lazy and used the old style ;)

**Comment by Kirek** [comment]
There where so many kernels that I only did it for linux46 and the utils :) maybe I will do the rest later. Also I noticed that in many kernels there are unused .patch files, maybe I will clean up that too.

All modules compile fine now. Uploading.
