### ISSUE TITLE
Update xfce4-power-manager to 1.6

### ISSUE THREAD

**Issue by schopenhauer** [manjaro/packages-extra#69]
Could you please bump the xfce4-power-manager version to the more recent version 1.6, as per the Xfce archive below?

http://archive.xfce.org/src/xfce/xfce4-power-manager/1.6/xfce4-power-manager-1.6.0.tar.bz2

Thank you.

**Comment by oberon2007** [comment]
Thank you for pointing this out. I see that the Arch package has been flagged out-of-date a month ago aleady. The package is more than a year old and has seen multiple updates since. I wonder if there is a reason for Arch to stay with the old one...
I have now written to the Arch packager. If he doesn't want to update the package we can do a temporary overlay.

**Comment by korrode** [comment]
The xfce-4.12 branch of xfce4-power-manager remains at versions 1.4.4:
http://git.xfce.org/xfce/xfce4-power-manager/log/?h=xfce-4.12

xfce4-power-manager > 1.4.x looks to be GTK3.

Unless someone can point out specific bugs or important new features, we should just wait for Arch.

**Comment by schopenhauer** [comment]
I have tested 1.5.x and 1.6.x branches on my machine. This solved problems I had suspending my Lenovo Carbon X1 (3rd gen.) when closing the lid.

**Comment by korrode** [comment]
Is this the issue where unless BOTH the on-battery and on-ac settings are set to suspend on lid-close, it doesn't?

i.e. do you have the lid action for _the other_ power state not set to suspend? and if you set it also to suspend does the issue go away?

**Comment by PhoronixSucks** [comment]
@oberon2007 Any progress on this issue? It's been over 11 days without any activity on this so I take it that it has been fixed?

**Comment by oberon2007** [comment]
No answer ...

**Comment by oberon2007** [comment]
My guess is that Arch is sticking to the xfce-4.12 branch.

**Comment by PhoronixSucks** [comment]
@oberon2007 Well if that's the case oberon I think going with a temporary overlay seems to be the best decision to do at this time to fix this issue.

**Comment by philmmanjaro** [comment]
Well, we won't replace the given **xfce4-power-manager** package. However I can release a **dev-package**.

**Comment by PhoronixSucks** [comment]
@philmmanjaro Okay that seems like a good route to take for now at least until the Arch packager updates but I'm possibly wondering if you can ship this package by default on the Manjaro 16.06 installation images due to the older version breaking suspend on laptops by default.

**Comment by korrode** [comment]
Is there some discussion somewhere about this broken suspend issue?

If you people experiencing it can test if applying this change (to 1.4.x release) fixes it, would be helpful.
http://git.xfce.org/xfce/xfce4-power-manager/commit/?id=a055fa2e42204b484b6000afe1e519321948c455

**Comment by PhoronixSucks** [comment]
@schopenhauer After testing the above commit from Korrode with the xfce-power-manager 1.4 package did the suspend issue for your laptop get fixed or is it still there?

**Comment by philmmanjaro** [comment]
I think followed patch needs also to be applied: http://git.xfce.org/xfce/xfce4-power-manager/commit/?id=ba081cefcb97c1903ce05d353cb0ee030e020195

**Comment by philmmanjaro** [comment]
Currently fails with:
```
org.freedesktop.PowerManagement.Inhibit.c:15:31: fatal error: gio/gunixfdlist.h: No such file or directory
compilation terminated.
Makefile:878: recipe for target 'xfce4_power_manager-org.freedesktop.PowerManagement.Inhibit.o' failed
make[3]: *** [xfce4_power_manager-org.freedesktop.PowerManagement.Inhibit.o] Error 1
make[3]: *** Waiting for unfinished jobs....
```

**Comment by oberon2007** [comment]
Are you maybe just missing a new gio-dependency by any chance?

**Comment by philmmanjaro** [comment]
**glib2** is installed, so I don't know what I might missing here. weird.

**Comment by oberon2007** [comment]
could it be **gio-sharp** ??

**Comment by oberon2007** [comment]
I've looked some more into this and I think I understand what you where trying to attempt in your PKGBUILD ... :wink: Looks a bit dirty, don't you think? :stuck_out_tongue_winking_eye: 
How about trying if the [master snapshot](http://git.xfce.org/xfce/xfce4-power-manager/commit/?id=719234b98ec876b491b11a86959510802fc33a99) of 2015-03-21 already solved the issue? Is't it possible that the later [commit](http://git.xfce.org/xfce/xfce4-power-manager/commit/?id=a055fa2e42204b484b6000afe1e519321948c455) only became necessary because of all the dbus related work up to that point?

**Comment by philmmanjaro** [comment]
No, the fix came with the dbus transition ...

**Comment by oberon2007** [comment]
bad news :stuck_out_tongue_closed_eyes:

**Comment by oberon2007** [comment]
another try ... ... This one fails with
```
xfpm-unique.c:226:39: error: ‘dbus_glib_xfce_unique_object_info’ undeclared (first use in this function)
                                      &dbus_glib_xfce_unique_object_info);
                                       ^
xfpm-unique.c: At top level:
xfpm-unique.c:229:13: error: conflicting types for ‘xfpm_unique_dbus_init’
 static void xfpm_unique_dbus_init (XfpmUnique *unique)
             ^
xfpm-unique.c:33:13: note: previous declaration of ‘xfpm_unique_dbus_init’ was here
 static void xfpm_unique_dbus_init  (XfpmUnique *unique);
             ^
xfpm-unique.c: In function ‘xfpm_unique_dbus_init’:
xfpm-unique.c:231:5: warning: implicit declaration of function ‘dbus_g_connection_register_g_object’ [-Wimplicit-function-declaration]
     dbus_g_connection_register_g_object (unique->priv->bus,
     ^
xfpm-unique.c:231:48: error: dereferencing pointer to incomplete type ‘XfpmUnique {aka struct _XfpmUnique}’
     dbus_g_connection_register_g_object (unique->priv->bus,
                                                ^
xfpm-unique.c: At top level:
xfpm-unique.c:236:17: error: conflicting types for ‘xfce_unique_ping’
 static gboolean xfce_unique_ping (XfpmUnique *unique,
                 ^
xfpm-unique.c:218:17: note: previous declaration of ‘xfce_unique_ping’ was here
 static gboolean xfce_unique_ping (XfpmUnique *unique,
                 ^
xfpm-unique.c:33:13: warning: ‘xfpm_unique_dbus_init’ used but never defined
 static void xfpm_unique_dbus_init  (XfpmUnique *unique);
             ^
Makefile:529: recipe for target 'libxfpmdbus_la-xfpm-unique.lo' failed
make[3]: *** [libxfpmdbus_la-xfpm-unique.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/build/xfce4-power-manager-exp/src/xfce4-power-manager-1.4.4/libdbus'
Makefile:434: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/build/xfce4-power-manager-exp/src/xfce4-power-manager-1.4.4/libdbus'
Makefile:516: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/build/xfce4-power-manager-exp/src/xfce4-power-manager-1.4.4'
Makefile:448: recipe for target 'all' failed
make: *** [all] Error 2
==> ERROR: A failure occurred in build().
```
Funny thing is I get the same error when I try to build the snapshot at the time of that latest patch!
Dependency missing maybe?

**Comment by oberon2007** [comment]
still: ``xfpm-unique.c:42:5: error: unknown type name ‘DBusGConnection’``

**Comment by philmmanjaro** [comment]
Yep, we miss something here ...

**Comment by oberon2007** [comment]
Looks like [this one](http://git.xfce.org/xfce/xfce4-power-manager/patch/?id=6eedcd26121fc99abe09d37f2c5d562450d485d0) would be necessary, too. But that looks like travelling into gtk3 land too far, doesn't it?

**Comment by philmmanjaro** [comment]
Try it. I think that is the one we miss. If it is gtk3 I don't know, but it makes sense. Take a fresh chroot without gtk3 in it and check what happens ... I thought I could skip it with `sed -i /xfpm-unique/d libdbus/Makefile.am` but it seems I was wrong. Didn't follow the complete patch ...

**Comment by oberon2007** [comment]
The problem is, for **xfpm-settings.h** to match the above patch it would also need the ["Start porting to GTK3.patch"](http://git.xfce.org/xfce/xfce4-power-manager/commit/?id=2087d60f7f535d920ba7590535ee42ba0c2fe394). And that one clearly includes:
```
-XDT_CHECK_PACKAGE([GTK], [gtk+-2.0], [gtk_minimum_version])
+XDT_CHECK_PACKAGE([GTK], [gtk+-3.0], [gtk_minimum_version]
```

**Comment by oberon2007** [comment]
To me it looks like the only sane way to go to either just use at least the 1.5 release, or otherwise keep the bug and offer the 1.6-dev package for those who need and want to use it ... :-/

**Comment by philmmanjaro** [comment]
Well, we already offer the 1.6 version as of now. I'll take another look at the patches. Maybe some backports are needed to get it working with gtk2 if ever :smile:

**Comment by philmmanjaro** [comment]
A way might be: patch, patch, revert first patch :smile:

**Comment by schopenhauer** [comment]
`xfce4-power-manager-dev` (i.e. development version, instead of `xfce4-power-manager`) seems to be installed by default on Manjaro 16.10. Replacing the `dev` version with the current `1.6.0.41.g9daecb5-1` solved some of my power management issues (e.g. auto-suspend, auto-blank-screen).

**Comment by philmmanjaro** [comment]
**xfce4-power-manager-dev** package got removed from our repos a while ago.

**Comment by schopenhauer** [comment]
In that case, I guess we can close this issue?
