### ISSUE TITLE
we need to downgrade orc temporarily (USB MIC ISSUE)

### ISSUE THREAD

**Issue by anexation** [manjaro/packages-extra#7]
Problem:
After performing pacman updates microphone audio is heavily distorted, even outside of applications that use the Mic.  When looking into the volume control panel or pavucontrol it shows the mic with a base input level of 100% instead of 0%. 

http://www.delawyn.com/2014/12/arch-linux-microphone-issues-after-12.html
https://bbs.archlinux.org/viewtopic.php?id=191392&p=1
https://bugzilla.gnome.org/show_bug.cgi?id=742303

Downgrade  to   "orc-0.4.22-2-x86_64.pkg.tar.xz"

**Comment by MrGizmo757** [comment]
I can confirm this happens on my system running Manjaro 0.8.11 As well as Stock Arch. 
Downgrading to orc 0.4.22-2 fixed the problem for me. Still not entirely sure what caused it.  
If for some reason this version is not in your package cache you can grab it here.  https://gist.github.com/EvanPurkhiser/7f4faa69a63dd9cdfe7b/raw/e0ffb847ed2ca66225f0db42a70e0e1e67513b45/orc-0.4.22-2-x86_64.pkg.tar.xz

**Comment by korrode** [comment]
Looks like there is a patch for pulseaudio to fix it, will have a package for you to test in a few mins...

**Comment by korrode** [comment]
Can you please update orc back to the latest package and try these pulseaudio packages with it:
http://www.paradoxcomputers.com.au/manjaro/packages/pulseaudio-fix_orc/

(be sure to restart the pulseaudio daemon after changing the pulse packages, if unsure reboot)

**Comment by anexation** [comment]
@ Rob, This resolves the issue, you can push them.. We need to watch for the version pulseaudio-5.99.2-1-x86_64.pkg.tar.xz thats in arch test it should require the patch also unless the arch maintainer fixes it or it gets fixed upstream..

**Comment by korrode** [comment]
Pushing to unstable and testing. Stable ~tomorrow
