### ISSUE TITLE
gtk 3.20 update breaks lightdm theming, greybird, emacs icons, and other things.

### ISSUE THREAD

**Issue by crocket** [manjaro/packages-extra#72]
I got an upgrade to gtk 3.20, and lots of things look visually broken.

1. lightdm looks broken in many themes.
2. With greybird, input box looks grey. With greenbird, things look better but still a bit broken.
3. emacs icons are gone
4. etc

**Comment by philmmanjaro** [comment]
It is a known issue that some of the themes are broken. Please use those which are already ported to GTK 3.20. A lot you can find at [gnome-look.org](http://gnome-look.org/index.php?xcontentmode=167). We are recommend to use the new default theme **vertex-maia**.

**Comment by crocket** [comment]
Although I appreciate the efforts you put into themes, vertex-maia is too bright for my taste. Vertex-maia-dark is too dark. I prefer subdued or mixed colors to primary colors.

**Comment by philmmanjaro** [comment]
@crocket: it is always sense of taste. We can't please everyone. There will come some more themes soon. As of now we will focus on our own themes we maintain. And **greybird** is not one of those. Please open an issue on their bug-tracker if you want to have it properly working.

**Comment by crocket** [comment]
Do you still maintain greenbird?

**Comment by philmmanjaro** [comment]
Well ...
```
artwork-greenbird
Greenbird Theme for Manjaro Linux - based on greybird (depreciated)
Updated on 12 Apr 2015 
```

**Comment by crocket** [comment]
The emacs icons issue is fixed now.

**Comment by crocket** [comment]
With vertex-maia, lightdm looks ok. I think it's safe to close the issue now.
