### ISSUE TITLE
[exo} overlay still needed?

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-extra#75]
Arch is meanwhile at [0.10.7](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/exo) and our patches are history.
Only other difference is we use additional build options
```
--libexecdir=/usr/lib/xfce4 \
--localstatedir=/var  \
--disable-static \
```
Do we need them?

**Comment by philmmanjaro** [comment]
We are currently using the Arch package already. The **XFCE** PKGBUILDs are more or less outdated. I update those when needed.

**Comment by oberon2007** [comment]
Ah. I forgot to check the actual package version in the repo :wink:
