### ISSUE TITLE
Possibly need to look into patching qt5-base

### ISSUE THREAD

**Issue by anexation** [manjaro/packages-extra#8]
If yall think it's important enough to apply a patch to qt5 because right now submenu's in applications in the system tray are broken and this patch is suppose to fix it..

https://codereview.qt-project.org/#/c/103280

If a packager can patch it and we can verify it's working submenus will be fixed in the system tray and we can update with the fix..

**Comment by manjaro** [comment]
I will look into it when I'm home:
<pre>git fetch https://codereview.qt-project.org/qt/qtbase refs/changes/80/103280/4 && git format-patch -1 --stdout FETCH_HEAD</pre>

**Comment by anexation** [comment]
update:

https://reviewboard.kde.org/r/122171/

**Comment by philmmanjaro** [comment]
Should be already added by now.
