### ISSUE TITLE
Andormeda-plasma

### ISSUE THREAD

**Issue by udeved** [manjaro/packages-extra#84]
We need to check that the template indeed selects all andromeda.
Icon theme still points to maia.

**Comment by philmmanjaro** [comment]
What do you mean by template?

**Comment by philmmanjaro** [comment]
@udeved: please report issues with the theme in the repo of the theme: https://github.com/manjaro/artwork-andromeda/commit/abe9c15898513e2a02ea5929807430a6b909fb69

**Comment by philmmanjaro** [comment]
Is this still relevant with the latest release of this theme?
