### ISSUE TITLE
Docker 1.11.2

### ISSUE THREAD

**Issue by 0006mathew** [manjaro/packages-extra#87]
I encountered a problem with docker version packaged by Manjaro. I listed my problem in issue tracker for docker and the docker team asked me to refer it to Manjaro dev team. 
https://github.com/docker/docker/issues/23730
Please look into it. I can provide additional logs if necessary.

**Comment by udeved** [comment]
Docker is an upstream arch package, afaik.
We don't package docker, arch does..

**Comment by oberon2007** [comment]
Yes, exactly. Here:
https://www.archlinux.org/packages/community/x86_64/docker/

**Comment by 0006mathew** [comment]
Thanks for reference
