### ISSUE TITLE
dkms-modules ready to replace per-kernel ones?

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-extra#88]
I realize that on my system the broadcom-wl-dkms module together with its pacman-hook works perfectly and that I can now live without the separate modules per kernel.
What's the deal with the dkms modules now. Are we continuing to build them per kernel anyway?

**Comment by udeved** [comment]
The deal is, dkms is nice, but it actually clashed with the mhwd repo on iso concept.

**Comment by oberon2007** [comment]
I see ...
