### ISSUE TITLE
Virtualbox-host-modules was not upgraded

### ISSUE THREAD

**Issue by kouros17** [manjaro/packages-extra#93]
Although the **virtualbox** is normally upgraded to 5.1.0.1 the **virtualbox-host-modules** remained in a previous version 5.0.24 (unstable branch). Virtualbox doesn't launch.

**Comment by oberon2007** [comment]
virtualbox has arrived from upstream about one hour ago. To build the extramodules for all kernel takes a llittle time ... :stuck_out_tongue_winking_eye:

**Comment by kouros17** [comment]
O.k oberon.

**Comment by oberon2007** [comment]
Now! :smiley: https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20160711/007789.html

**Comment by kouros17** [comment]
Yeep...works flawlessly.
Thanks a lot oberon! :+1:
