### ISSUE TITLE
Module nvidia_drm missing from nvidia driver

### ISSUE THREAD

**Issue by mac1202** [manjaro/packages-extra#94]
Hi I try to enable kms from nvidia proprietary driver, based on the archwiki I need to add nvidia, nvidia_modeset, nvidia_uvm and nvidia_drm to my initramfs. The problem is the nvidia driver from manjaro doesn't provide the nvidia_drm module.
```
ls /lib/modules/4.6.2-1-MANJARO/extramodules/
nvidia.ko.gz  nvidia-modeset.ko.gz  nvidia-uvm.ko.gz  version  vhba.ko.gz
```

**Comment by budimanjojo** [comment]
You don't need to enable KMS on proprietary driver

**Comment by mac1202** [comment]
Based on archwiki i need it for wayland.

**Comment by budimanjojo** [comment]
Wayland in Nvidia doesn't work in any DE yet. So there's no point on trying it. https://www.phoronix.com/scan.php?page=news_item&px=NVIDIA-Wayland-Discussion
I think the support for KMS is not being enabled by Manjaro team yet.

**Comment by philmmanjaro** [comment]
Seems we [missed it](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/nvidia&id=98b86afe991a96808688c210191ed9a517ea6b89) ...

```
upgpkg: nvidia 364.16-2
fix the missing nvidia-drm kernel module
```
